app:
 logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
server:
  port: '8080'

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
    
  datasource:
   #Desarrollo(cuenta blacker)
   #url: jdbc:oracle:thin:@//192.168.1.49:1521/DBA
   url: jdbc:oracle:DBblacker@//BlackerJM:1521/xe
   
   
   username: DBblacker
   password: 1234567
    
   driver-class-name: oracle.jdbc.OracleDriver
   hikari:
      maximum-pool-size: 15
      pool-name: namePool
        
  jackson:
    default-property-inclusion: NON_NULL
    #locale: es_PE
    #serialization:
      #fail-on-self-references: false
        
 

